name: Scraping Automatique des Agences

on:
  schedule:
    - cron: '0 7 * * *' # S'exécute automatiquement tous les jours à 7h du matin
  workflow_dispatch: # Permet de lancer le script manuellement depuis GitHub

jobs:
  build:
    runs-runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          pip install requests beautifulsoup4

      - name: Lancer le scraper
        run: python scraper.py

      - name: Publier les mises à jour sur GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add annonces.json
          git commit -m "Mise à jour automatique des annonces" || exit 0
          git push
